// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMCntr727Lgj3wCPLMINWTAO21u7l_CA4',
    appId: '1:963791065717:web:dd64319f3e48aa30ad1e3c',
    messagingSenderId: '963791065717',
    projectId: 'evently-task2',
    authDomain: 'evently-task2.firebaseapp.com',
    storageBucket: 'evently-task2.firebasestorage.app',
    measurementId: 'G-GZ0B8W43DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVlz5BOKeoYgIBelSV5Stc3c8bQ0jwTpk',
    appId: '1:963791065717:android:b6588db3d364eeb8ad1e3c',
    messagingSenderId: '963791065717',
    projectId: 'evently-task2',
    storageBucket: 'evently-task2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDq_SRQo5V8AeWAsgOMQYS-zG21oHFoeM',
    appId: '1:963791065717:ios:fbcab0737cdedd66ad1e3c',
    messagingSenderId: '963791065717',
    projectId: 'evently-task2',
    storageBucket: 'evently-task2.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC132',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDq_SRQo5V8AeWAsgOMQYS-zG21oHFoeM',
    appId: '1:963791065717:ios:fbcab0737cdedd66ad1e3c',
    messagingSenderId: '963791065717',
    projectId: 'evently-task2',
    storageBucket: 'evently-task2.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC132',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMCntr727Lgj3wCPLMINWTAO21u7l_CA4',
    appId: '1:963791065717:web:7dea6260a9fcc22dad1e3c',
    messagingSenderId: '963791065717',
    projectId: 'evently-task2',
    authDomain: 'evently-task2.firebaseapp.com',
    storageBucket: 'evently-task2.firebasestorage.app',
    measurementId: 'G-L9ZGWKTTGW',
  );

}